### ISSUE TITLE
Random effect summary names

### ISSUE THREAD

**Issue by athowes** [awstringer1/aghq#4]
Using `summary` I get:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/29818116/188733573-5d595acd-1cc2-4b8e-b0d6-aec87cab4bd5.png">

I think what's happening is that in [`summary.marginallaplace`](https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/04-aghq.R#L1198) the column names should be:

```{r}
  randomeffectsummary <- data.frame(
    mean = means,
    median = medians,
    mode = modes,
    sd = sds,
    `2.5%` = quants[ ,1],
    `97.5%` = quants[ ,2]
  )
```

But they are overwritten with:

```{r}
colnames(randomeffectsummary) <- colnames(summ$summarytable)
```

And for some reason in `summary.aghq` the mode is removed and mode is in a different position:

```{r}
  # thesummary <- thesummary[ ,c('mean','median','mode','sd','2.5%','97.5%')]
  thesummary <- thesummary[ ,c('mean','sd','2.5%','median','97.5%')]
```

So I think the first commented out version of `thesummary` should be used to prevent this. Is there a reason why it's commented out?

**Comment by awstringer1** [comment]
Finally fixed this. I just removed the `mode` column. Not sure why I bothered to report that in the first place, it's not a particularly relevant quantity.

**Comment by athowes** [comment]
Thanks! On whether or not to include the mode, I think there are use cases where you could plausibly want it, and some other software packages choose to include it in summary output, so perhaps this is something that we may want to include. Also possible to provide an option to include. Perhaps having many options gets overwhelming, and it's possible to calculate other ways if someone really wants.
