### ISSUE TITLE
Small suggestions for `sample_marginal.marginallaplace` method

### ISSUE THREAD

**Issue by athowes** [awstringer1/aghq#5]
1. Use `<-` rather than `=` for consistency https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L836
2. `K` defined but not used in function https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L837
3. Group code about `numcores` together (i.e. move this to where `numcores` is defined) https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L841
4. `tt` defined https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L860 but then not used later, and instead redefined here https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L875
5. Suggesting using a variable other than `k` for indexes, as `k` is used to correspond to number of quadrature points for a particular dimension in the rest of the package
6. Consider different choice of variable than `d` for the length of the fixed effects, as it is previously used for the length of the random effects in the same function https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L891
7. Standardise the output structure of the random effect and fixed effect samples https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/03-summary-statistics.R#L908 This would be done in `sample_marginal.aghq` by adding the names of `theta`

**Comment by awstringer1** [comment]
Done all except 7, not sure what you mean there. Feel free to add a PR since we know how to do that now :)
