### ISSUE TITLE
Bug in `normalize_logpost` with `k = 1`

### ISSUE THREAD

**Issue by athowes** [awstringer1/aghq#6]
In the function `normalize_logpost` if you set `k = 1`, that is one quadrature point, the Laplace approximation is used rather than going through the process of creating a grid:

https://github.com/awstringer1/aghq/blob/9f796e81e1f12deecf3908c9f802b017920457a5/R/02-normalization.R#L83

This should be fine but the object output (for me this is a `numeric` with `attr(*, "logarithm") == TRUE`) is not the same as if you have `k > 1` where you'll get a named list with elements:

```{r}
list(
  nodesandweights = nodesandweights,
  grid = thegrid,
  lognormconst = lognormconst
)
```

I'd suggest altering this function to produce these outputs for `k = 1` too, so that it's always be predictable as input to other functions.

**Comment by awstringer1** [comment]
Was this fixed by your PR?

**Comment by athowes** [comment]
Yes, working now!

```
> eb_quad <- aghq::marginal_laplace_tmb(obj, k = 1, startingvalue = obj$par)
> eb_quad
aghq object. 

Use summary(...) to see more detailed information,

plot(...) to see plots of marginal distributions, and 

?compute_moment to see a list of useful summary methods.
```
